server:
  port: 7777
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.234.131:8848

    gateway:
      discovery:
        locator:
          enabled: true #启用 DiscoveryClient 网关集成的标志  网上说：(让gateway可以发现nacos中的微服务)
          lower-case-service-id: true # 在谓词和过滤器中小写 serviceId 的选项
      routes:
#        - id: routeDemo
#          uri: http://localhost:8081 #转发的路径
#          predicates:
#            - Path=/server
