server:
  port: 8734
#  port: 8729
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://192.168.31.206:5432/cswf_mes
mybatis:
  mapperLocations: classpath:mapper/*/*.xml
eureka:
  instance:
    prefer-ip-address: true
    #实例名
    instance-id: mes-stock-dev:${server.port}
      #    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${eureka.instance.non-secure-port}
      #    #配置状态页面为swagger-bootstrap-ui（封装swagger的开源项目，用户界面比较友好，推荐一个）接口页面，默认为项目的info端点页面
      #    #    status-page-url: http://${eureka.instance.ip-address}:${eureka.instance.non-secure-port}/v2/api-docs
      #    #设置外网IP号(就是natapp 中的域名)
    #    #    ip-address: server.natappfree.cc
    #    #设置外网端口号（natapp 的端口）
    #    #    non-secure-port: 33106
  client:
    service-url:
      #euraka地址
      defaultZone: http://192.168.31.206:8720/eureka/
#      defaultZone: http://localhost:8720/eureka/
